### PR TITLE
Adding back required property

### PR DESCRIPTION
**Pull request by bhelx**
Adding back required so we can distinguish b/w required and nullable

### CODE REVIEW

**Comment by bhelx** [comment]
Okay, we can land this now.

**Comment by nilslice** [comment]
should there be some validation to catch the case where something is both required and nullable? I _think_ that would be invalid? or, do we want to be able to represent that state. still thinking about the use case.

**Comment by bhelx** [comment]
> should there be some validation to catch the case where something is both required and nullable? I think that would be invalid? or, do we want to be able to represent that state. still thinking about the use case.

No, all combinations are valid. For an idea of what this would look like in Go, see the description of this PR: https://github.com/dylibso/xtp-go-bindgen/pull/20

**Review by mhmd-azeez — APPROVED** [review]
lgtm, let's get this merged so that i can merge them into my PR

**Pull request merged**
